### ISSUE TITLE
Using get_json() doesn't work when # abstractive summaries != # extractive summaries

### ISSUE THREAD

**Issue by michaelomahony-edgetier** [guyfe/Tweetsumm#3]
Trying to convert the DialogWithSummaries object to json/string format using get_json() throws "TypeError: 'NoneType' object is not iterable" exception since some of the summaries are None when the number of abstractive summaries and extractive summaries are unequal for any given dialogue.

`Cell In[2], line 82, in DialogWithSummaries.get_json(self)
     80 abstractive_summaries_to_json = list()
     81 for summ in self.abstractive_summaries:
---> 82     abst_json = [txt for txt in summ ]
     83     abstractive_summaries_to_json.append(abst_json)
     85 result = {
     86     'dialog' : dialog,
     87     'summaries' : {
   (...)
     91     }
     92 }

TypeError: 'NoneType' object is not iterable`

**Comment by garrettsomers** [comment]
Resolved by skipping the list comprehension if summ is None

```
        for summ in self.abstractive_summaries:
            if summ is None: continue
            abst_json = [txt for txt in summ ]
```
